---
driver:
  name: vagrant
  network:
    - ["private_network", {ip: "33.33.33.37"}]

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
- name: ubuntu-14.04
  driver:
    customize:
      memory: 1024
  driver_config:
    box: opscode-ubuntu-14.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box

suites:
- name: vsftpd
  run_list:
  - recipe[vsftpd]
